  language: python
  python:
    - 3.5
    - nightly

  sudo: required

  services:
    - docker
    - git

  bevore_install:
    - docker build -t happyday-image .
    - docker run -d -p 8080:5000 -name happyday happyday-image
    - docker ps -a

  script:
    - pytest
