  language: python

  python:
    - 3.5
    - nightly

  sudo: required

  services:
    - docker

  install:
    - docker build -t happyday-image .
    - docker run -d -p 8080:5000 --name happyday happyday-image

  bevore_install:
    - docker run -ti happyday-image

  script:
    - docker ps | grep -q happyday
    - docker run happyday-image /bin/bash -c "cd happyday-service; pytest"
    - pytest

